### DISCUSSION TITLE
How do you use Conditioned<string> properties?

### DISCUSSION THREAD

**Discussion by flcdrg** [sharpliner/sharpliner#427] [Q&A]
Might be a dumb question, but trying to find an example of how you use `If` with a `Conditioned<string>`-typed property.

**Comment by premun** [comment]
Hey,
I think the intended usage is this (let's say `DisplayName` is `Conditioned<string>`):

```
new Stage("stageName")
{
	DisplayName = If.IsBranch("main")
                                .Value("job_1")
                             .Else
                                 .Value("job_2")
}
```

**Reply by flcdrg** [reply]
I tried that (on both a Job and also a Stage in my PR branch), but it fails with this error:

```
(Line: 1, Col: 1, Idx: 0): Expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS, got MappingEnd [D:\git\azure-pipelines-sharpliner\_build\src\Pipelines.csproj
```

**Reply by flcdrg** [reply]
Ah.. I think I need to add `.EndIf` and then it doesn't error.

**Reply by flcdrg** [reply]
But that now generates invalid YAML 😞 

```csharp
new Job("Example")
        {
            DisplayName = If.IsBranch("main")
                    .Value("job_1")
                    .Else
                    .Value("job_2")
                    .EndIf,

    Steps = [
        Powershell.Inline("Write-Host 'Hello-World'").DisplayAs("Hello world")
    ]
    }
]
```

```yaml
- job: Example
  displayName:
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}: job_1
    ${{ else }}: job_2
```

**Reply by premun** [reply]
Ah, apologies, let me give this a go

**Reply by premun** [reply]
I see, the right YAML would be this?

```yaml
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    displayName: job_1
  ${{ else }}:
    displayName: job_1
```

**Reply by flcdrg** [reply]
Yes, that would work

**Reply by premun** [reply]
This is interesting, not even YAML has a good solution to having multiple conditional blocks within an object (not a list):

Consider this:
```yaml
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    displayName: Publish to nuget.org
  ${{ else }}:
    displayName: Test publishing to nuget.org
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/production') }}:
    pool:
      name: Azure Pipelines
      vmImage: windows-2019
  ${{ else }}:
    pool:
      name: Azure Pipelines
      vmImage: windows-2022
```

This actually fails because the second `${{ else }}` block overrides the first one (as this is just a map).
