### ISSUE TITLE
API Mock-up

### ISSUE THREAD

**Issue by premun** [sharpliner/sharpliner#11]
This is a living issue. Edit the description directly.

```csharp
public class MainPipeline : Sharpliner.PipelineDefinition
{
    protected override string TargetFile => "/azure-pipelines.yml";

    protected override Pipeline Pipeline => new()
    {
        Name = "$(Date:yyyMMdd).$(Rev:rr)",

        Triggers = new[]
        {
            new()
            {
                Branches = new[] { "main", "production" },
                IsBatch = true,
                Exclude = new[] { "tools/*" },
            }
        },

        Prs = new[]
        {
            new()
            {
                Branches = new[] { "main" },
                AutoCancel = true,
            }
        },

        Variables = new[]
        {
            Variable("Configuration", "Release"),
            Variable("DOTNET_SKIP_FIRST_TIME_EXPERIENCE", true),
            Group("PR keyvault variables"),

            If.Equal("variables['Build.Reason']", "PullRequest")
                .Variable("TargetBranch", "$(System.PullRequest.SourceBranch)"),

            If.NotEqual("variables['Build.Reason']", "PullRequest")
                .Variable("TargetBranch", "$(Build.SourceBranch)"),

            If(And(Equals("variables['Build.SourceBranch']", "refs/heads/production"), NotEquals("Configuration", "Debug")))
                .Variable("PublishProfileFile", "Prod")
                .Variable("AzureSubscription", "NetHelix"),
        },

        Stages = new[]
        {
            new()
            {
                Jobs = new[]
                {
                    new Job("PublishClient", "Publish wheel packages")
                    {
                        Timeout = TimeSpan.FromMinutes(30),
                        Pool = new HostedPool(vmImage: "windows-2019"),
                        Checkout = 'self',
                        Clean = true,
                        Steps = new[]
                        {
                            new BashTask("Install wheel and twine"
                                "pip install wheel==0.33.6 twine==2.0.0"),

                            new TwineAuthenticateTask(artifactFeed: "public/$(HelixClientFeedName)"),

                            new BashTask("Publish Helix Installer Wheel"
                                @"python $(HelixInstallerDir)\setup.py egg_info --tag-build $(HelixScriptsVersion) bdist_wheel
                                  python -m twine upload -r $(HelixClientFeedName) --config-file $(PYPIRC_PATH) $(HelixInstallerDir)\dist\*.whl"),
                        ]
                    },

                    new Job("BuildClient", "Build solution")
                    {
                        Timeout = TimeSpan.FromMinutes(30),
                        Pool = new HostedPool(vmImage: "windows-2019"),
                        Checkout = 'self',
                        Clean = true,
                        DependsOn = new[] { "PublishClient" },
                        Steps = new[]
                        {
                            If("and(eq(variables['Build.Reason'], 'PullRequest'), ne(variables['Build.SourceBranch'], 'refs/heads/production'))",
                                new PowerShellTask("Enforce GitHub issue link presence"
                                    "eng/enforce-issue.ps1 -PullRequestId $(System.PullRequest.PullRequestId) -AccessToken $(System.AccessToken)")),

                            new UseDotNetTask("Use .NET 2.1.x SDK", type: DotNetPackageType.SDK, version: "2.1.x"),

                            new CustomDotNetCoreCLITask("Build Helix.Machines.sln", "msbuild") {
                                Projects = new[] { "Helix.Machines.sln" },
                                Arguments = new[] { "-v:m", "-m:1", "-nr:false", "-restore", "-t:Build;Publish" },
                            }
                        }
                    }
                }
            }
        }
    };
}
```

This is the source pipeline that we are trying to model:
```yaml
name: $(Date:yyyMMdd).$(Rev:rr)

trigger:
  batch: true
  branches:
    include:
      - main
      - production
  paths:
    exclude:
      - tools/*

pr:
  autoCancel: true
  branches:
    include:
      - main
  paths:
    exclude:
      - tools/*

variables:
  - name: Configuration
    value: Release
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - group: PR keyvault variables

  - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      - name: TargetBranch
        value: $(System.PullRequest.SourceBranch)
  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
      - name: TargetBranch
        value: $(Build.SourceBranch)

  - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/production') }}:
      - name: PublishProfileFile
        value: Prod
      - name: AzureSubscription
        value: NetHelix

stages:
  - stage: Build
    jobs:
      - job: PublishClient
        displayName: Publish wheel packages
        timeoutInMinutes: 30
        pool:
          vmImage: "windows-2019"

        steps:
          - script: pip install wheel==0.33.6 twine==2.0.0
            displayName: Install wheel and twine

          - task: TwineAuthenticate@1
            displayName: Twine Authenticate
            inputs:
              artifactFeed: public/$(HelixClientFeedName)

          - script: |
              python $(HelixInstallerDir)\setup.py egg_info --tag-build $(HelixScriptsVersion) bdist_wheel
              python -m twine upload -r $(HelixClientFeedName) --config-file $(PYPIRC_PATH) $(HelixInstallerDir)\dist\*.whl
            displayName: Create/Publish Helix Installer Wheel

      - job: Build
        displayName: Build solution
        dependsOn: PublishClient
        timeoutInMinutes: 30
        pool:
          vmImage: "windows-2019"

        steps:
          - checkout: self
            clean: true

          - ${{ if and(eq(variables['Build.Reason'], 'PullRequest'), ne(variables['Build.SourceBranch'], 'refs/heads/production')) }}:
              - powershell: eng/enforce-issue.ps1 -PullRequestId $(System.PullRequest.PullRequestId) -AccessToken $(System.AccessToken)
                displayName: Enforce GitHub issue link presence

          - task: UseDotNet@2
            displayName: Use .NET 2.1.x SDK
            inputs:
              packageType: sdk
              version: 2.1.x

          - task: DotNetCoreCLI@2
            inputs:
              command: custom
              custom: msbuild
              projects: Helix.Machines.sln
              arguments: >-
                -v:m
                -m:1
                -nr:false
                -restore
                -t:Build;Publish
```
