### ISSUE TITLE
Allow conditional values in Dictionaries (e.g. template parameters)

### ISSUE THREAD

**Issue by premun** [sharpliner/sharpliner#142]
We should allow following:

```yaml
      parameters:
        runtimeFlavor: ${{ parameters.runtimeFlavor }}
        stagedBuild: ${{ parameters.stagedBuild }}
        buildConfig: ${{ parameters.buildConfig }}
        ${{ if eq(parameters.passPlatforms, true) }}:					<---- THIS
          platforms: ${{ parameters.platforms }}
        helixQueueGroup: ${{ parameters.helixQueueGroup }}
        crossBuild: true
        crossrootfsDir: '/crossrootfs/arm64'
        ${{ insert }}: ${{ parameters.jobParameters }}
```
