### ISSUE TITLE
Schedules is written out as singular instead of plural

### ISSUE THREAD

**Issue by ModernRonin** [sharpliner/sharpliner#162]
Example:
```csharp
public class CreatePulumiImagePipeline : SingleStagePipelineDefinition
{
    public override SingleStagePipeline Pipeline =>
        new()
        {
            Name = "CreatePulumiImages",
            Schedule = new List<ScheduledTrigger> { new("31 01 * * *") },
            Variables = { Group("CommonPipelineVariables") },
            Jobs = ...
        };
    public override string TargetFile => "../Pipelines/CreatePulumiImage.yml";
}
```

comes out as
```yaml
name: CreatePulumiImages

schedule:                       # should be "schedules"
- cron: 31 01 * * *

variables:
- group: CommonPipelineVariables

jobs: ...
```

Thanks for this library! Before I tried Nuke, but that is really rather ugly. Conversely, Sharpliner has a much cleaner concept (generating yamls) and allows to describe ones pipelines very nicely.
