### ISSUE TITLE
PowershellFileTask generates invalid yaml

### ISSUE THREAD

**Issue by ModernRonin** [sharpliner/sharpliner#168]
Hi,

maybe doing something wrong, but
```csharp
new PowershellFileTask("tools/scripts/RunDocker.ps1")
{
    Arguments = args,
    DisplayName = "Running docker image",
    Pwsh = true
};
```

creates this yaml:
```yaml
name: CreateReleasableImages

trigger:
  branches:
    include:
    - master
    - STABLE

variables:
- group: CommonPipelineVariables

- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true

jobs:
- job: job
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    fetchDepth: 1

  - powershell: tools/scripts/RunDocker.ps1
    targetType: filepath
    arguments: -image ourcontainerregistry.azurecr.io/tools/pulumi:latest -command "/usr/bin/pwsh -Command {./vso.ps1; ./LogIntoAzure.ps1; ./RunPulumi.ps1 }" -doEnableDocker $true -$volumeMounts $(Build.SourcesDirectory)/image-maker:~/project
    displayName: Running docker image
    pwsh: true
```

which DevOps doesn't like:
>/tools/Pipelines/CreateReleasableImages.yml (Line: 31, Col: 5): Unexpected value 'targetType'
/tools/Pipelines/CreateReleasableImages.yml (Line: 32, Col: 5): Unexpected value 'arguments'
/tools/Pipelines/CreateReleasableImages.yml (Line: 34, Col: 5): Unexpected value 'pwsh'

Looking at the [documentation of the task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops), I get the impression that `powershell` is only for inline scripts and if one wants to use a file, one has to use the `PowerShell@2` task.
