### ISSUE TITLE
DotNetPublishCoreCliTask: wrong command is being serialized

### ISSUE THREAD

**Issue by jshield** [sharpliner/sharpliner#181]
``` yaml
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: public
```

should be

``` yaml
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
```
