### ISSUE TITLE
Be able to automatically bootstrap new pipelines in AzDO

### ISSUE THREAD

**Issue by jshield** [sharpliner/sharpliner#188]
this a low priority request.

It'd be nice to be able to run a single pipeline that validates the pipelines are good and correct during a PullRequest, and when merged into the trunk branch, have the job running be able to create/update the pipelines in the project owning the repo using the SYSTEM_ACCESSTOKEN or another env var, based on attributes that can be added or overridable properties.

i.e. [AutomaticallyRegisterPipeline(string name, string? folder)]

It could potentially be achieved by having a task similar to the ValidateYamlsArePublished in AzureDevOpsDefinition

**Comment by premun** [comment]
Hi,

Thanks for the idea! Do you actually have a use case where you create new pipelines this often?

**Comment by jshield** [comment]
Hey, thanks for the fast response.

I could potentially manage this through something like terraform and the azure devops provider, but given I'm mostly a .NET developer, it'd be nice to be able to do it closer to the pipeline definition themselves.

It's personally for me less about frequency, and more about consistency. Another example of something in the same problem space would be synchronizing a pipeline trigger's path inclusion exclusion rules with branch policy build validation path rules as well.

Although yes in my case, as I provide devops pipeline support for multiple teams across multiple repositories/projects, I do standup a lot of pipelines regularly. particularly when new services are being stood up. 

Cheers for considering it though.

**Comment by premun** [comment]
I don't have a good opinion this but similar topics have come up in some discussions and issues in this repo already. I am a little bit torn on what is the purpose of Sharpliner.

1. One side is that it is a general purpose mostly non-opinionated generic tool that lets you do pipelines and just that but well. It is however very low-level with respect to the YAML scheme (some more high level exceptions are some fluent APIs like the .NET CLI task).
2. On another side there is great potential to make opinionated libraries full of functionality and if generic enough, could be a nice drop-in solution for usual scenarios (build + test + deploy). Sort of a marketplace approach where you have libraries of steps.
This should probably be clearly separated maybe into another NuGet with libraries like what you are doing already (https://github.com/sharpliner/sharpliner/issues/175) so that it's clear we're in a higher layer of concerns than the core Sharpliner lib.

My personal experience is that every project eventually needs some custom step where you diverge from the generic approach and then things break because you need to either add some configuration into the generic library (making it more complex) or you need to stop using the library a go your own way.

Now, to your specific suggestion.

If I would be implementing this, I would not go the way of adding C# code to Sharpliner that calls AzDO APIs to create a pipeline. I would for sure create a library of pipeline steps that would do it. Same like `ValidateYamlsArePublished` is implemented. This means that it would become an opinionated library like I am describing above. For this reason, I would first probably prefer to see your implementation for your own use case that you have and then think about if and how to generalize it and incorporate into some Sharpliner extension/task library.

That being said, **I very much like your idea of tagging pipelines with attributes**. I would consider whether it wouldn't be valuable to put following functionality into the core Sharpliner library:

> Allow registering custom attributes together with some publish actions (callbacks) into the publish process. You could add custom attributes to definitions and when these are being published as YAML, your callbacks would be called during the process.

What are your thoughts on all this? Did I manage to describe my concerns and where I am coming from?

**Comment by premun** [comment]
Actually, on another thought - maybe attributes are too much of an over-engineering.. It would just be easier to let people overload the `Publish()` method on pipelines (or add some other methods/events like `OnBeforePublish` or `OnAfterPublish`) and this would have the same effect with a simpler approach.

**Comment by jshield** [comment]
Going in reverse:

Yeah upon reflection (heh get it) attributes are probably overkill, and overridable properties is probably the correct approach for sharpliner as a low level library. although sometimes they are useful to provide that layer of metadata in a clear obvious place.

I sealed TargetFile on my classes and require a TemplateOutput(PipelineActivity activity, Type parameterType) attribute to make it clear from looking at the class declaration where the template gets generated, based on conventions, but yes you are correct highly subjective and hard to apply to all cases.

example:

``` csharp 

public record PulumiDeployment : IDeployment
{
    
    [YamlMember(Order = 0)]
    public string Type => GetType().ToTemplatePath();

    [NotUsedByStepTemplate]
    public string DependsOn { get; set; } = "";

    [NotUsedByStepTemplate]
    public bool RunDuringPullRequests { get; set; } = true;

    public string Project { get; set; }
    public string Stack { get; set; }
    
    public AzureServicePrincipal ServiceConnection { get; set; }
    [NotUsedByStepTemplate]
    public AzureResourceGroup ResourceGroup { get; set; }
    public AzureKeyVault ManagementKeyVault { get; set; }
}

public abstract class TypedStepTemplateDefinitionBase<T> : StepTemplateDefinition
{
    public sealed override string TargetFile => GetType().GetTargetFileFromAttribute();

    public override TargetPathType TargetPathType => TargetPathType.RelativeToGitRoot;

    public sealed override List<TemplateParameter> Parameters => typeof(T).AsTemplateParameters().ToList();

    protected string PipelineWorkspace => "$(Pipeline.Workspace)";
    

    // Helper Method for referencing properties as passed parameters on <T>
    public string Use<TR>(
        Expression<Func<T, TR>> selector)
    {
        var member = ((MemberExpression) selector.Body).Member;
        var name = member.GetCustomAttribute<JsonPropertyNameAttribute>()?.Name ?? member.Name.ToCamelCase();
        return parameters[name];
    }
    
    protected TR UseNamed<TR>(
        Expression<Func<T, TR>> selector) where TR: Named<TR>, new()
    {
        var member = ((MemberExpression) selector.Body).Member;
        var name = member.GetCustomAttribute<JsonPropertyNameAttribute>()?.Name ?? member.Name.ToCamelCase();
        return new TR {Name = parameters[name]};
    }

    protected Condition IsManual => Condition("eq(variables['Build.Reason'], 'Manual')");

    protected readonly AzureBashInlineTaskBuilder AzureCli = new();


}

[TemplateOutput(PipelineActivity.Deploy, typeof(PulumiDeployment))]
internal class DeployPulumiSteps : TypedStepTemplateDefinitionBase<PulumiDeployment>
{
    private string PulumiStateStorageSasToken => $"PULUMI-STATE-{Use(deployment => deployment.Stack)}-STORAGE-SAS-TOKEN";
    private string PulumiStateStorageAccount => $"PULUMI-STATE-{Use(deployment => deployment.Stack)}-STORAGE-ACCOUNT";

    protected string ProjectPath => $"{PipelineWorkspace}/self/{Use(artifact => artifact.Project)}";


    public override ConditionedList<Step> Definition
    {
        get
        {
            return new()
            {
                Extensions.Tasks.NugetAuthenticate("Authenticate nuget against azure artifact feeds"),
                new AzureKeyVaultTask()
                {
                    AzureSubscription = UseNamed(deployment => deployment.ServiceConnection),
                    KeyVaultName = UseNamed(deployment => deployment.ManagementKeyVault),
                    SecretsFilter = new[]
                    {
                        PulumiStateStorageAccount, 
                        PulumiStateStorageSasToken
                    }
                },
                AzureCli.FromResourceFile(UseNamed(deployment => deployment.ServiceConnection),$"{GetType().Namespace}.setup-pulumi.sh") with
                {
                    Env = new()
                    {
                        { "AZURE_STORAGE_ACCOUNT", $"$({PulumiStateStorageAccount})" },
                        { "AZURE_STORAGE_SAS_TOKEN", $"$({PulumiStateStorageSasToken})" },
                        { "STACK", Use(deployment => deployment.Stack) }
                    }, DisplayName = $"Configuring Pulumi for {Use(deployment => deployment.Stack)}"
                },
                AzureCli.FromResourceFile(UseNamed(deployment => deployment.ServiceConnection),$"{GetType().Namespace}.run-pulumi.sh") with
                {
                    Env = new()
                    {
                        { "AZURE_STORAGE_ACCOUNT", $"$({PulumiStateStorageAccount})" },
                        { "AZURE_STORAGE_SAS_TOKEN", $"$({PulumiStateStorageSasToken})" },
                        { "STACK", Use(deployment => deployment.Stack) },
                        { "AZURE_KEYVAULT_NAME", UseNamed(deployment => deployment.ManagementKeyVault)}
                    }, 
                    WorkingDirectory = ProjectPath, 
                    DisplayName = $"Running Pulumi for {Use(deployment => deployment.Stack)}"
                }
            };
        }
    }
}
```

``` yaml

# steps/pulumi/steps-deploy.yml

###
### DO NOT MODIFY THIS FILE!
###
### This YAML was auto-generated from DeployPulumiSteps
### To make changes, change the C# definition and rebuild its project
###

parameters:
- name: type
  type: string
  default: pulumi

- name: project
  type: string

- name: stack
  type: string

- name: serviceConnection
  type: string

- name: managementKeyVault
  type: string

steps:
- task: NuGetAuthenticate@0
  displayName: Authenticate nuget against azure artifact feeds

- task: AzureKeyVault@2
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    keyVaultName: ${{ parameters.managementKeyVault }}
    secretsFilter: PULUMI-STATE-${{ parameters.stack }}-STORAGE-ACCOUNT,PULUMI-STATE-${{ parameters.stack }}-STORAGE-SAS-TOKEN

- task: AzureCLI@2
  displayName: Configuring Pulumi for ${{ parameters.stack }}
  inputs:
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: >-
...
    azureSubscription: ${{ parameters.serviceConnection }}
  env:
    AZURE_STORAGE_ACCOUNT: $(PULUMI-STATE-${{ parameters.stack }}-STORAGE-ACCOUNT)
    AZURE_STORAGE_SAS_TOKEN: $(PULUMI-STATE-${{ parameters.stack }}-STORAGE-SAS-TOKEN)
    STACK: ${{ parameters.stack }}

- task: AzureCLI@2
  displayName: Running Pulumi for ${{ parameters.stack }}
  inputs:
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: >-
...
    azureSubscription: ${{ parameters.serviceConnection }}
    workingDirectory: $(Pipeline.Workspace)/self/${{ parameters.project }}
  env:
    AZURE_STORAGE_ACCOUNT: $(PULUMI-STATE-${{ parameters.stack }}-STORAGE-ACCOUNT)
    AZURE_STORAGE_SAS_TOKEN: $(PULUMI-STATE-${{ parameters.stack }}-STORAGE-SAS-TOKEN)
    STACK: ${{ parameters.stack }}
    AZURE_KEYVAULT_NAME: ${{ parameters.managementKeyVault }} # AzureKeyVault

``` 

The events/virtual methods approach is probably correct for providing an extension framework, that way additional before/after callbacks could be added, and provided through external libraries without pulling in the whole world through the sharpliner core library.

That way I could add a method that would then call AzDo and perform logic to update service configuration (register new pipelines/update names) without having to bloat the underlying goals of sharpliner. 

One of my side projects is a linter for AzDo pipelines using the PipelineParser in the Azure DevOps Pipeline Agent, so again I could add a post publish hook to run the linter on the resulting template to ensure it meets our style, naming, etc...

global and per pipeline hooks is probably ideal so being able to do something like the below:

``` csharp

class YourCustomConfiguration : SharplinerConfiguration
{
    public override void Configure()
    {
        // Insert your overrides here
        Serialization.PrettifyYaml = false;
        Serialization.UseElseExpression = true;
        Serialization.IncludeHeaders = false;
        Validations.DependsOn = ValidationSeverity.Off;
        Validations.Name = ValidationSeverity.Error;
        Hooks.Pipeline.BeforePublish = (ISharplinerDefinition definition, Pipeline pipeline) =>
        {
            return PipelineLinter.Lint(pipeline); //bool on false fail build
        };
        Hooks.Pipeline.AfterPublish = (ISharplinerDefinition definition, Pipeline pipeline, string yaml) =>
        {
            var registration = typeof(definition).GetCustomAttribute<AutomaticallyRegisterPipeline>();

            if (registration != null && Environment.GetEnvironmentVariable("BUILD_REASON") == "IndividualCI")
            {
                var id = AzDoUpdatePipelineRegistration.Register(definition.GetTargetPath(), registration.Name,
                    registration
                        .Folder); // find pipelines using TargetPath, if none are found create one under folder with name pointing to file, otherwise rename, and move if an existing pipeline is present.
                AzDoUpdatePipelineRegistration.EnsureBuildValidationIsPresentOn("main", id,
                    pipeline.Trigger); // ensure that Build Validation on branch is enabled and configure path rules based on trigger path rules
            }
        };
    }
}

```

would be fantastic.

Your concerns are totally valid, and I appreciate and respect your position as to the scope of what sharpliner should do.
