### ISSUE TITLE
Automatically wrap string expressions in condition in apostrophes

### ISSUE THREAD

**Issue by thomhurst** [sharpliner/sharpliner#227]
Take this variable condition:

```csharp
        Variables =
        {
            StartsWith("refs/head/feature/", variables.Build.SourceBranch).Variable("myvariable", "pr-variable")
                .Else.Variable("myvariable", "other-variable"),
        },
```

The yaml being produced is:

```yaml
variables:
- ${{ if startsWith($(Build.SourceBranch), refs/head/feature/) }}:
  - name: myvariable
    value: pr-variable
- ${{ else }}:
  - name: myvariable
    value: other-variable
```

I get this exception:
![image](https://user-images.githubusercontent.com/30480171/186944149-ed1b5c6f-908c-406f-97d1-4cf3c7ffb8e4.png)

I think both of these values in the Contains/StartsWith/EndsWith conditions need to be made into strings. 
i.e. adding quotes around them
