### ISSUE TITLE
It should be possible to inject a parameter reference to any type of pipeline

### ISSUE THREAD

**Issue by premun** [sharpliner/sharpliner#255]
### Problem
It is currently not possible to create following YAML template:

```yaml
parameters:
  agentOs: ''
  steps: []

steps:
- ${{ if eq(parameters.agentOs, 'Windows_NT') }}:
  - ${{ parameters.steps }}
```

There is no mechanism to inject parameter reference instead of an arbitrary piece of the definition.

The C# for this would look something like this:
```csharp
public class RunOnWindowsTemplate : StepTemplateDefinition
{
    public override string TargetFile => "run-on-windows.yml";

    public override List<Parameter> Parameters => new()
    {
        StringParameter("agentOs"),
        StepListParameter("steps"),
    };

    public override ConditionedList<Step> Definition => new()
    {
        If.Equal(parameters["agentOs"], "Windows_NT")
            .Step(/* New stuff goes here */)
    };
}
```
