### ISSUE TITLE
How to use BooleanParameter as value in task?

### ISSUE THREAD

**Issue by mathiasi** [sharpliner/sharpliner#266]
I've got this example:

```csharp
Parameters =
{
    BooleanParameter("myBool", "", false),
},
Jobs = new() {
    Job("job") with
    {
        Steps = new()
        {
            DotNet.Test("*Test.csproj") with
            {
                DisplayName = "Dotnet Test",
                TestRunTitle = "Title",
                Arguments = "--no-build --configuration Release --collect \"Code coverage\"",
                ContinueOnError = parameters["myBool"]  // <--- ERROR: Cannot implicitly convert type 'Sharpliner.AzureDevOps.ConditionedExpressions.ParameterReference' to 'bool'

            }
        }
    }
}
```

Is there a way to pass the parameter on to the input of the task?

**Comment by mathiasi** [comment]
Only workaround I could think of was
```csharp
DotNet.Test("*Test.csproj") with
{
    DisplayName = "Dotnet Test",
    TestRunTitle = "Title",
    Arguments = "--no-build --configuration Release --collect \"Code coverage\"",
    Inputs = new()
    {
        { "ContinueOnError", parameters["myBool"] }
    }
}
```
but this looks less ideal.

**Comment by premun** [comment]
Hey,
Thanks for opening this issue. I agree that this is a very useful feature and should be supported. Unfortunately, I think it will require quite a bit of work as technically a variable can be put in place of basically anything. I think it might have a solution where we create a wrapper type that could be "T or expression" but I will have to do some experiments to verify it can be done.

I will get back to you soon about this.

**Comment by mathiasi** [comment]
I was also thinking a wrapper would be needed. Maybe something like Conditioned<T>. I did notice also that the following syntax didn't seem to be supported either:
```yaml
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    testRunTitle: "Title"
    projects: |
      *.Test.csproj
    ${{ if eq(parameters.myBool, true) }}:  
      arguments: 'some arguments'
    ${{ if eq(parameters.myBool, false) }}: 
      arguments: 'some other arguments'
```

Maybe one solution could cover both scenarios
