### ISSUE TITLE
Add support for each-expressions

### ISSUE THREAD

**Issue by asos-neildownes** [sharpliner/sharpliner#281]
Would it be possible to add the ability to generate "each-expressions" in the auto generated yaml files?  

I'd like to be able to iterate over a collection, like an array of environments, and use each environment variable as an input parameter to a yaml template.  Please see example below.

```
- ${{ each env in parameters.environments}}:
  - template: ../stages/provision.yml
    parameters:
      environment: ${{env}}
      ${{ if eq(env.deploymentEnvironmentName, '') }}:
        deploymentEnvironment: ${{ parameters.applicationName }} - ${{ env.name }}
      ${{else}}:
        deploymentEnvironment: ${{ env.deploymentEnvironmentName }}
      regions: ${{parameters.regions}}
      pipelinePath: ${{parameters.pipelinePath}}
      applicationName: ${{parameters.applicationName}}
```
