### ISSUE TITLE
Conditionally define `Arguments` for DotNetCoreCLI@2 task

### ISSUE THREAD

**Issue by michaelhahn-doka** [sharpliner/sharpliner#284]
I'm currently developing an internal template/pipeline library to use within various internal projects.
At the current point I have the requirement to conditionally define the arguments input for the `DotNetCoreCLI@2` task based on a pipeline parameter which should result in the following yaml:

```yaml
- task: DotNetCoreCLI@2
  displayName: Create NuGet package
  inputs:
    command: 'pack'
    ${{ if eq(parameters.includeSymbols, true) }}:
      arguments: '--no-restore --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg'
    ${{ else }}:
      arguments: '--no-restore --no-build'
```

Is there any possibility to conditionally define that arguments parameter e.g. something like that?
```csharp
DotNet.Pack(ProjectFile) with
{
  Arguments = If.Equal(parameters[IncludeSymbols], "true")
      .Value("--configuration $(BuildConfiguration) --no-restore --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg")
      .Else.Value("--configuration $(BuildConfiguration) --no-restore --no-build")
}
```

**Comment by premun** [comment]
Alright, this one is a bit verbose but you can do this:
```yaml
DotNet.Pack("ProjectFile") with
{
    Inputs = new()
    {
        {
            If.Equal(parameters["IncludeSymbols"], "true"), new TaskInputs()
            {
                ["arguments"] = "--configuration $(BuildConfiguration) --no-restore --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg"
            }
        },
        {
            If.NotEqual(parameters["IncludeSymbols"], "true"), new TaskInputs()
            {
                ["arguments"] = "--configuration $(BuildConfiguration) --no-restore --no-build"
            }
        }
    },
},
```

which produces this:

```yaml
- task: DotNetCoreCLI@2
      inputs:
        command: pack
        packagesToPack: ProjectFile
        ${{ if eq(parameters.IncludeSymbols, true) }}:
          arguments: --configuration $(BuildConfiguration) --no-restore --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
        ${{ if ne(parameters.IncludeSymbols, true) }}:
          arguments: --configuration $(BuildConfiguration) --no-restore --no-build
```
