### ISSUE TITLE
bug: Using variables for template parameters value

### ISSUE THREAD

**Issue by Meir017** [sharpliner/sharpliner#375]
the following code is not valid:

```csharp
public class TestPipeline : ExtendsPipelineDefinition
{
    public override string TargetFile => "test-pipeline.yml";
    public override TargetPathType TargetPathType => TargetPathType.RelativeToGitRoot;

    public override PipelineWithExtends Pipeline => new PipelineWithExtends
    {
        Variables = 
        [
            VariableTemplate("variables.yml") // This is a template that defines buildType & templateName
        ],

        Extends = new("base-pipeline.yml", new()
        {
            ["buildType"] = variables["buildType"],
            ["templateName"] = variables["templateName"]
        })
    };
}
```

generates this:

```yaml
extends:
  template: base-pipeline.yml
  parameters:
    buildType: $(buildType)
    templateName: $(templateName)

variables:
- template: variables.yml
```

the correct way is:
```yaml
extends:
  template: base-pipeline.yml
  parameters:
    buildType: ${{ variables.buildType }}
    templateName: ${{ variables.templateName }}

variables:
- template: variables.yml
```

using the `${{ variables.<var-name> }}`.

how can we generate this type of template? I need to use the `CompileTimeExpression` and not the `MacroExpression`

https://github.com/sharpliner/sharpliner/blob/365b9c214a5a7027a8983f51ad24ad6d62a2db99/src/Sharpliner/AzureDevOps/InlineStringConditionHelper.cs#L9-L17

Is this correct?

**Comment by premun** [comment]
Does the `$()` notation not work though? It should be semantically the same?

**Comment by Meir017** [comment]
getting the error `The 'buildType' parameter value '$(buildType)' is not a valid value.` which means the variable was not found.

**Comment by premun** [comment]
I see..
Maybe we want the `TaskInput` to turn those into the right references and force the `${{ }}` form

**Comment by Meir017** [comment]
@premun it's not going through the `TaskInputs` type, it's the `TemplateParameters` type

**Comment by Meir017** [comment]
> I see.. Maybe we want the `TaskInput` to turn those into the right references and force the `${{ }}` form

I'm not sure I follow this suggestion

**Comment by premun** [comment]
It's basically your suggestion but I'd put it onto the `ConditionedDictionary` directly maybe

**Comment by premun** [comment]
I am honestly not sure how these things work.

Like if you have this:

#### pipeline.yml
```yaml
stages:
- template: template.yml
  parameters:
    buildType: ${{ variables.buildType }}
```

#### template.yml
```yaml
parameters:
- name: buildType
  type: string

stages:
- ${{ if eq(parameters.buildType, 'Debug') }}:
	- stage: Foo
    ...
- ${{ else }}:
    ...
```

So my understanding was that it gets evaluated during compile time and we can use `${{ if }}` over it in the template but not sure whether those `$()` expressions only evaluate during runtime and the `eq` won't work.
