### ISSUE TITLE
feature request: Defining a template that extends another template

### ISSUE THREAD

**Issue by Meir017** [sharpliner/sharpliner#377]
azure pipelines supports defining a template that extends another template.

for example:

`template-a.yml`:
```yml
parameters:
- name: paramA
  type: string
- name: paramB
  type: number

extends:
  template: `template-b.yml`:
  parameters:
...
```

`template-b.yml`:
```yml
parameters:
...
stages:
...
```

My issue here is that `public abstract class TemplateDefinition<T>` exposes a `public abstract ConditionedList<T> Definition { get; }` which will not work to render an `extends` object.

my current workarround is to define a type that extends the `ExtendsPipelineDefinition` type and set just the `Parameters` & `Extends` properties of the `PipelineWithExtends Pipeline` property
