### ISSUE TITLE
feature request: allow passing variable & parameter to template parameter

### ISSUE THREAD

**Issue by Meir017** [sharpliner/sharpliner#378]
would be nice to be able to pass variable/parameter to template parameters:

```csharp
private class MyTestPipeline : PipelineDefinition
{
   private static readonly Variable myVar = new Variable("myVar", "myValue");
   private static readonly Parameter myParam = StringParameter("myParam");
   public override Pipeline Pipeline => new()
   {
      Variables = [myVar],
      Parameters = [myParam],
      Stages =
      [
        StageTemplate("the-stage", new()
         {
            ["myParam"] = myParam,
            ["myVar"] = myVar,
         })
      ]
   };
}
```

generates the following YAML:

```yaml
parameters:
- name: myParam
  type: string
variables:
- name: myVar
  value: myValue
stages:
- template: the-stage.yml
  parameters:
    myParam: ${{ parameters.myParam }}
    myVar: ${{ variables.myVar }}
```

expected YAML:
```yaml
parameters:
- name: myParam
  type: string
variables:
- name: myVar
  value: myValue
stages:
- template: the-stage
  parameters:
    myParam:
      name: myParam
      type: string
    myVar:
      name: myVar
      value: myValue
```
