### ISSUE TITLE
Allow using typed-parameters templates with external templates 

### ISSUE THREAD

**Issue by Meir017** [sharpliner/sharpliner#401]
In some scenarios we use pipeline templates from external repositories

To allow using the typed-parameter templates we would need a way to override the template's `TargetFile` property value (and add a `@repo` suffix)

I wonder if we could add a utility method for the template classes, something like

```diff
public abstract class ExtendsTemplateDefinition<TParameters> : ExtendsTemplateDefinition where TParameters : class, new()
{
+  public Template<Extends> AsExternalTemplate(string path)
}
```

similar change for `StageTemplateDefinition<TParameters>`, `JobTemplateDefinition<TParameters>`, `StepTemplateDefinition<TParameters>`, `VariableTemplateDefinition<TParameters>`

**Comment by premun** [comment]
Can you show me the intended usage?

Should we also have `StepTemplate(...)` having `ExternalStepTemplate(...)`?

**Comment by Meir017** [comment]
@premun I think the issue here is only for the parameter-typed templates due to us having the implicit convertion operator to `Template<T>`.

in order to ensure the typed-paramteres template is up-to-date, maybe we should have this change allow us to generate the external template as local templates removing our dependency on the external git-repo that provided the templates (removing the need to specify the `resource.repositories.<repository>.ref` to a version matching the nuget package)

**Comment by Meir017** [comment]
@premun for example - https://github.com/dotnet/arcade/blob/992d2e5d76cccb72ad611ba2141e25db86cd59bd/azure-pipelines.yml#L38C1-L52C19

```yml
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: $(DncEngInternalBuildPool)
      image: windows.vs2019.amd64
      os: windows
    sdl:
      policheck:
        enabled: true
      tsa:
        enabled: true


    stages:
    - stage: build
```

Any typed-parameters template for this will probably not be able to live in that repository (at least not yet)
