### ISSUE TITLE
enhancement: Name Validation preventing using a parameter for stage name

### ISSUE THREAD

**Issue by Meir017** [sharpliner/sharpliner#402]
consider the following code

```cs
public class DemoStageTemplate : StageTemplateDefinition
{
    public override TargetPathType TargetPathType => TargetPathType.RelativeToGitRoot;
    public override string TargetFile => "demo-template.yaml";

    public override List<Parameter> Parameters => 
    [
        StringParameter("stageName", defaultValue: "build_stage"),    
    ];

    public override ConditionedList<Stage> Definition => 
    [
        Stage(parameters["stageName"]) with
        {

        }
    ];
}
```

when building this produces the following error:

Sharpliner.targets(20,5): error :   Validation of definition DemoStageTemplate failed!
Sharpliner.targets(20,5): error :     - Invalid character found in name `${{ parameters.stageName }}`, only A-Z, a-z, 0-9, and underscore are allowed

after disabling the name-validating using a custom configuration, the generated yaml is correct:

```yaml
###
### DO NOT MODIFY THIS FILE!
###
### This YAML was auto-generated from DemoStageTemplate
### To make changes, change the C# definition and rebuild its project
###

parameters:
- name: stageName
  type: string
  default: build_stage

stages:
- stage: ${{ parameters.stageName }}

```

## Suggestion

Modify the `NameValidation` class to check if a name matches the parameters pattern `${{ parameters.<name> }}` and if so then validate the <name> parameter exists and is a string
