### ISSUE TITLE
feature request: Setting stage.dependsOn to a parameters as a single value

### ISSUE THREAD

**Issue by Meir017** [sharpliner/sharpliner#403]
the following doesn't compile

```cs
public class DemoStageTemplate : StageTemplateDefinition
{
    public override TargetPathType TargetPathType => TargetPathType.RelativeToGitRoot;
    public override string TargetFile => "demo-template.yaml";

    public override List<Parameter> Parameters => 
    [
        ObjectParameter<string>("dependsOn", defaultValue: [])
    ];

    public override ConditionedList<Stage> Definition => 
    [
        Stage("main-stage") with
        {
            DependsOn = parameters["dependsOn"], // <- this is invalid, changing to - [parameters["dependsOn"]] will generate an array of values
        }
    ];
}
```

goal for template yaml:

```yml
parameters:
- name: dependsOn
  type: object
  default: []

stages:
- stage: main-stage
  dependsOn: ${{ parameters.dependsOn }}
```

## Suggestion

Make the DependsOn be a new type that extends from `ConditionedList<string>` and has an implicit cast from `ParametersReference` & `string`.
Then, add a custom yaml-converter for this type then when the value is a list with a single item it serializes to a string instead of a array-of-string
