### ISSUE TITLE
feature request: Allow using a boolean parameter as an if condition

### ISSUE THREAD

**Issue by Meir017** [sharpliner/sharpliner#404]
I have a template with boolean parameters and conditional stages based on these parameters:

```yaml
parameters:
- name: runStage
  type: boolean
  default: false

stages:
- ${{ if parameters.runStageA }}:
  - template: ../stage-template-a
```

Defining a template like:
```cs
public class DemoStageTemplate : StageTemplateDefinition
{
    public override TargetPathType TargetPathType => TargetPathType.RelativeToGitRoot;
    public override string TargetFile => "demo-template.yaml";

    public override List<Parameter> Parameters =>
    [
        BooleanParameter("runStage", defaultValue: false)
    ];

    public override ConditionedList<Stage> Definition =>
    [
        If.Condition(parameters["runStage"])
            .StageTemplate("stage-template-a")
    ];
}
```

generates the following yaml

```yml
###
### DO NOT MODIFY THIS FILE!
###
### This YAML was auto-generated from DemoStageTemplate
### To make changes, change the C# definition and rebuild its project
###

parameters:
- name: runStage
  type: boolean
  default: false

stages:
- ${{ if ${{ parameters.runStage }}:
  - template: stage-template-a
```

# Suggestion

add another overload for `If.Condition` that takes a `ParameterReference` and outputs `${{ if parameters.<param-name> }}`
```diff
public class IfConditionBuilder
{
+ public IfCondition Condition(ParameterReference condition)
}

public class IfConditionBuilder<T>
{
+ public IfCondition<T> Condition(ParameterReference condition)
}
```
