### ISSUE TITLE
feature request: Serialize simple variables as dictionary

### ISSUE THREAD

**Issue by trevorlacey-msft** [sharpliner/sharpliner#405]
Variables are always serialized as a list to objects. It a collection of variables contains only simple types (non-objects) without readonly flag, it would be nice to serialize them as a dictionary for conciseness.

For example:
```cs
return new Stage("myStageName", "myStageDisplayName")
{
    Variables = new List<VariableBase>
    {
        new Variable("stringVar", "hello"),
        new Variable("intVar", 42),
        new Variable("boolVar", true),
        new Variable("enumVar", StringComparison.Ordinal),
    }
};
```

This serializes to:
```yml
- stage: myStageName
  displayName: myStageDisplayName
  variables:
  - name: stringVar
    value: hello

  - name: intVar
    value: 42

  - name: boolVar
    value: true

  - name: enumVar
    value: Ordinal
```

It would be nice if it instead serialized to:
```yml
- stage: myStageName
  displayName: myStageDisplayName
  variables:
    stringVar: hello
    intVar: 42
    boolVar: true
    enumVar: Ordinal
```
