### ISSUE TITLE
Stage DisplayName is not conditioned

### ISSUE THREAD

**Issue by flcdrg** [sharpliner/sharpliner#424]
I want to be able to set the displayName of a stage conditionally. eg. 

```yaml
      - stage: thing
        ${{ if eq(parameters.WhatIf, true) }}:
          displayName: "Release: (WhatIf)"
        ${{ else }}:
          displayName: "Release"
```

The current type of DisplayName is string, 

https://github.com/sharpliner/sharpliner/blob/c2c1ed298335fad767b0b330e5b5fac05a1d4ac1/src/Sharpliner/AzureDevOps/Model/Stage.cs#L23C20-L23C32

whereas I think it needs to be `Conditioned<string>?` (like `Step` and `Job`)
