### ISSUE TITLE
Referencing a parameter in Each results in invalid YAML

### ISSUE THREAD

**Issue by flcdrg** [sharpliner/sharpliner#426]
Given this code:

```csharp
public class EachWithParameterPipeline : PipelineDefinition
{
    private static readonly ObjectParameter Stages = ObjectParameter("Stages", "Environment names (do not edit)", new ConditionedDictionary()
    {
        { "Dev", string.Empty}
    });

    public override string TargetFile => "each-pipeline.yml";
    public override TargetPathType TargetPathType => TargetPathType.RelativeToGitRoot;

    public override Pipeline Pipeline => new()
    {
        Parameters =
        [
            Stages
        ],

        Stages = [
            Each("stage", parameters[Stages.Name])
                .Stage(new Stage("${{ stage }}")
                {

                    Jobs = [
                        new Job("Example")
                                {
                            Steps = [
                                Powershell.Inline("Write-Host 'Hello-World'").DisplayAs("Hello world")
                            ]
                            }
                        ]
                })
        ]
    };
}
```

The following YAML is generated. Note the extra `${{`

```yaml
parameters:
- name: Stages
  displayName: Environment names (do not edit)
  type: object
  default:
    Dev: ''

stages:
- ${{ each stage in ${{ parameters.Stages }}:
  - stage: ${{ stage }}
    jobs:
    - job: Example
      steps:
      - powershell: |-
          Write-Host 'Hello-World'
        displayName: Hello world
```

Referencing the `Stages` field directly like this also results in the same incorrect output:

```csharp
Each("stage", Stages)
```
