### ISSUE TITLE
Conditioned scalar values not working in non-list scenarios

### ISSUE THREAD

**Issue by premun** [sharpliner/sharpliner#429]
## Problem

As discussed [here](https://github.com/sharpliner/sharpliner/discussions/427), if we have scalar `Conditioned<>` values, such as `Conditioned<string>`, if statements are not working with these.

Consider this code:
```csharp
new Stage("Example")
{
    // DisplayName is Conditioned<string>
	DisplayName = If.IsBranch("main")
                                .Value("job_1")
                             .Else
                                 .Value("job_2")
}
```
which produces this YAML:
```yaml
- stage: Example
  displayName:
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}: job_1
    ${{ else }}: job_2
```
whereas the following YAML should be produced:
```yaml
- stage: Example
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    displayName: job_1
  ${{ else }}:
    displayName: job_1
```

This does not reproduce with non-scalar values (objects or lists).

With objects it works as the serialized value is again an object:
```yaml
jobs:
- job: Job
  pool:
    ${{ if eq('A', 'B') }}:
      name: pool-A
    ${{ else }}:
      name: pool-B
```

Same with lists:
```yaml
  dependsOn:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - stage_1

  - ${{ else }}:
    - stage_2
```

The problem is that if we are serializing an object like this:

```csharp
public record Stage : IDependsOn
{
    public Conditioned<string>? DisplayName { get; init; }
}
```

we need to affect the serialization before it serializes the member name already.
So when we emit `displayName: ` into the YAML, it's already too late, because we need to emit `${{ if ... }}` instead.

## Possible solution?

I am not sure what's the right solution. Technically, we'd need to use this in many places. So implementing a custom `IYamlConvertible` on every class seems quite complicated.

Maybe we can put `YamlIgnore` onto the `DisplayName` and instead have some other special property and somehow make the serialization process serialize those when their priority hits. If we had that, we could implement it as a source generator possibly and tag all the other scalar values in the project.

Another solution could be if we had the following implemented: https://github.com/sharpliner/sharpliner/issues/122. Then it would be possible to do this easily. But that's also a large rewrite.

**Comment by premun** [comment]
@Meir017 @flcdrg this one I believe is now one of the largest shortcomings of the library at the moment.

**Comment by Meir017** [comment]
@premun to be sure I understand - the syntax we want to have here is
```cs
new Stage("Example")
{
    // DisplayName is Conditioned<string>
    DisplayName = If.IsBranch("main")
                     .Value("job_1")
                  .Else
                      .Value("job_2")
}
```

and we want it to generate
```yaml
- stage: Example
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    displayName: job_1
  ${{ else }}:
    displayName: job_1
```

is this correct?
