### ISSUE TITLE
Unable to Use ParameterReference with TimeoutInMinutes Property

### ISSUE THREAD

**Issue by ManelRosPuig** [sharpliner/sharpliner#435]
Hey! First, thank you for the amazing work on Sharpliner! 💙

I really like the idea of passing the timeout as a TimeSpan and having it automatically converted into minutes in the generated YAML output. However, this design makes it impossible to use a **ParameterReference** for **TimeoutInMinutes** because it is a read-only property.

Here's an example of the YAML output I want to generate:
```yaml
parameters:
- name: task_name
  type: string
  default: NPM_task
- name: timeout_in_minutes
  type: number
  default: 30

steps:
- task: Npm@1
  name: ${{ parameters.task_name }}
  timeoutInMinutes: ${{ parameters.timeout_in_minutes }}
```

To achieve this, I tried the following Sharpliner code:

```csharp
public class Npm : StepTemplateDefinition
{
    public override string TargetFile => "tasks/externals/npm.yml";

    public override List<Parameter> Parameters => [
        new StringParameter("task_name", "NPM_task"),
        new NumberParameter("timeout_in_minutes", 30)
    ];

    public override ConditionedList<Step> Definition => [
        new AzureDevOpsTask("Npm@1")
        {
            Name = parameters["task_name"],
            TimeoutInMinutes = parameters["timeout_in_minutes"] // Error here
        }
    ];
}
```

However, I encountered the following error:
```
CS0200: The property or indexer 'Step.TimeoutInMinutes' cannot be assigned to because it is read-only.
```
### Question/Request
Is there a specific reason why TimeoutInMinutes is read-only? Since it’s a Conditioned<int>?, shouldn’t it accept a ParameterReference for dynamic assignment? Or is there a better approach I might be missing?

Thank you for considering this! Let me know if more details are needed :)
